version: '3' 
services:
  docker-nebteans:
    image: openkbs/protege-docker-x11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protege-docker-x11
    environment:
      - DISPLAY=${DISPLAY:-localhost:0}
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/data-docker/protege-docker-x11/.Protege:/home/developer/.Protege
      - ${HOME}/data-docker/protege-docker-x11/Workspace:/home/developer/workspace-protege
      - ${HOME}/data-docker/protege-docker-x11/Plugin:/home/developer/protege-x11/plugins
