version: '3' 
services:
  docker-nebteans:
    image: openkbs/protege-docker-x11
    build:
      context: ./Dockerfile
    container_name: protege-docker-x11
    environment:
      - DISPLAY=${DISPLAY:-localhost:0}
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./docker.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.protege-docker-x11:/home/developer/.protege-docker-x11
      - ./workspace:/home/developer/workspace

